[package]
name = "pdxindoorsoccer-ical"
version = "0.1.0"
authors = ["David Orchard <if_coding@fastmail.com>"]
edition = "2018"

[dependencies]
icalendar = "0.5.0"
chrono = "0.4.6"
chrono-tz = "0.5.0"
failure = "0.1.5"
regex = "1.1.0"
lazy_static = "1.2.0"
heck = "0.3.1"
reqwest = "0.9.10"
encoding_rs = "0.8.16"
structopt = "0.2.14"
clap-verbosity-flag = { git = "https://github.com/dlo9/clap-verbosity-flag" }
caseless = "0.2.1"

[patch.crates-io]
structopt = { git = "https://github.com/dlo9/structopt" }
icalendar = { git = "https://github.com/dlo9/icalendar-rs" }
